### ISSUE TITLE
Problem with recursive schemas.

### ISSUE THREAD

**Issue by jcoyne** [kevindew/openapi3_parser#13]
Given this schema (which is valid):
https://gist.github.com/jcoyne/054937bd4f260c88ff69e21f99bb22cf

When I run this code:
```ruby
schemas = Openapi3Parser.load_file('openapi.yml').components.schemas
schema = schemas['DescriptiveBasicValue']
schema.properties.map.each { |k, v| puts k }
```

I get this error:
```
Traceback (most recent call last):
       16: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/field.rb:77:in `errors'
       15: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/field.rb:105:in `validate'
       14: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/field.rb:117:in `run_validation'
       13: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/fields/reference.rb:59:in `validate'
       12: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/source/resolved_reference.rb:28:in `errors'
       11: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/source/resolved_reference.rb:50:in `build_errors'
       10: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object.rb:43:in `valid?'
        9: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object.rb:47:in `errors'
        8: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object_factory/node_builder.rb:8:in `errors'
        7: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object_factory/node_builder.rb:26:in `errors'
        6: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object_factory/node_builder.rb:51:in `validate'
        5: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object_factory/validator.rb:13:in `call'
        4: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object_factory/validator.rb:23:in `call'
        3: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object_factory/validator.rb:36:in `check_required_fields'
        2: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.8.1/lib/openapi3_parser/node_factory/object.rb:67:in `required_fields'
        1: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/2.6.0/forwardable.rb:224:in `field_configs'
SystemStackError (stack level too deep)
```

**Comment by kevindew** [comment]
Hello 👋, I'm sorry to hear you hit a bug with this gem. Thanks for providing the source file and code to replicate.

I've just pushed up a [branch](https://github.com/kevindew/openapi3_parser/tree/fix-recursive-problem) that fixes the issue you've flagged:

```
irb(main):001:0> openapi = Openapi3Parser.load_file('openapi.yml')
=> Openapi3Parser::Document(openapi_version: 3.0, root_source: Openapi3Parser::Source(input: /Users/kevindew/dev/openapi3_parser/openapi.yml))
irb(main):002:0> openapi.valid?
=> true
irb(main):003:0> openapi.components.schemas['DescriptiveBasicValue'].properties.map.each { |k, v| puts k }
value
type
structuredValue
=> [nil, nil, nil]
```

I'll plan to push it out in a release tomorrow. If you're interested in trying it out in your project beforehand that'd be super helpful.

**Comment by jcoyne** [comment]
Wonderful! Thank you. I’ll take a look tomorrow morning.

**Comment by kevindew** [comment]
@jcoyne sure, ok great. I'll release this version and mark this issue as resolved.
