### ISSUE TITLE
Tried to load unspecified class: Time

### ISSUE THREAD

**Issue by aeden** [kevindew/openapi3_parser#7]
When trying to parse https://developer.dnsimple.com/v2/openapi.yml with 0.5.1:

```
/Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser/source_input.rb:49:in `contents': Tried to load unspecified class: Time (Openapi3Parser::Error::UnparsableInput)
	from /Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser/source.rb:37:in `data'
	from /Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser/document.rb:95:in `initialize'
	from /Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser.rb:27:in `new'
	from /Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser.rb:27:in `load_file'
	from generate.rb:5:in `<main>'
```

**Comment by aeden** [comment]
Awesome! Thanks for getting it turned around so quick. I'll pull the branch with the change and fix those items in the spec that fail validation.

**Comment by aeden** [comment]
So I set up my Gemfile to use the branch from git, but I'm still seeing the same error. Not sure if I'm doing something wrong on my end. Here is the bundle output:

```
$ bundle install
Fetching https://github.com/kevindew/openapi3_parser.git
Fetching gem metadata from https://rubygems.org/.....
Resolving dependencies...
Using bundler 1.16.1
Using concurrent-ruby 1.0.5
Using i18n 1.1.0
Using ruby-enum 0.7.2
Using commonmarker 0.17.11
Using openapi3_parser 0.5.1 from https://github.com/kevindew/openapi3_parser.git (at fix-dates-in-yaml@f118b9b)
Bundle complete! 1 Gemfile dependency, 6 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.]
```

When I attempt to parse the YAML file, I am still seeing the error:

```
/Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser/source_input.rb:49:in `contents': Tried to load unspecified class: Time (Openapi3Parser::Error::UnparsableInput)
	from /Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser/source.rb:37:in `data'
	from /Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser/document.rb:95:in `initialize'
	from /Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser.rb:27:in `new'
	from /Users/anthonyeden/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/openapi3_parser-0.5.1/lib/openapi3_parser.rb:27:in `load_file'
	from generate.rb:6:in `<main>'
```

Any thoughts are appreciated.

**Comment by aeden** [comment]
FWIW, loading the JSON version worked fine, so I'm moving forward with that. Happy to test additional changes on the branch though if it helps.

**Comment by kevindew** [comment]
Glad to hear it's working with JSON 👍 

I'm not sure what the problem you're having when trying out the commit. This is my experience:

```
➜  openapi3_parser git:(f118b9b) git checkout f118b9b
HEAD is now at f118b9b Don't die as horridly when YAML parses a Date/Time
➜  openapi3_parser git:(f118b9b) bundle console
irb(main):001:0> doc = Openapi3Parser.load_url("https://developer.dnsimple.com/v2/openapi.yml")
=> Openapi3Parser::Document(openapi_version: 3.0, root_source: Openapi3Parser::Source(input: https://developer.dnsimple.com/v2/openapi.yml))
irb(main):002:0> doc.valid?
=> false
```

Does look a bit like it's failing in the exact same place from the trace so I'd wonder if somehow it wasn't executing the updated code.
